- name: "table"
  pose:
    position:
      x: 0.0
      y: 0.4
      z: -0.09
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1  # SolidPrimitive.BOX    
    dimensions: [1.0, 1.0, 0.01] # [length, width, height]

- name: "wall1"
  pose:
    position:
      x: 0.0
      y: 0.9
      z: 0.15
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1  # SolidPrimitive.BOX    
    dimensions: [1.0, 0.01, 0.5] # [length, width, height]

- name: "wall2"
  pose:
    position:
      x: 0.50
      y: 0.40
      z: 0.15
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1  # SolidPrimitive.BOX    
    dimensions: [0.01, 1.0, 0.5] # [length, width, height]

- name: "wall3"
  pose:
    position:
      x: -0.50
      y: 0.40
      z: 0.15
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1  # SolidPrimitive.BOX    
    dimensions: [0.01, 1.0, 0.5] # [length, width, height]

- name: "wall4"
  pose:
    position:
      x: 0.0
      y: -0.1
      z: 0.15
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1  # SolidPrimitive.BOX    
    dimensions: [1.0, 0.01, 0.5] # [length, width, height]


