<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>gcode</name>
  <version>0.0.0</version>
  <description>Pure C++ G-code parser library</description>
  <maintainer email="berarishika@gmail.com">rishika2024</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>catch2_vendor</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
